### ISSUE TITLE
awsmobile projects do not translate well across git pull/push.

### ISSUE THREAD

**Issue by michaelcuneo** [aws/awsmobile-cli#103]
I've got a project I work on at work. On the weekends I sometimes wish to take a look at it, but the version I have here at home, doesn't function. awsmobile errors all the time. There is either no project in the folder, or no such file or directory on certain files, reinitialising it just messes it up completely, and I've never been able to get it to work in two places at once. Isn't this stage-able at all?

**Comment by UnleashedMind** [comment]
Sorry to hear that Michael. 
Could you please provide more detailed description of the problems that you have encountered? So we can help you to find the best way to resolve the issues. 
Please let us know the version of the cli and the exact error messages.

**Comment by michaelcuneo** [comment]
The version is the same on both sides. I'm literally pushing the project with git... then pulling it at home. Standard .gitignore for a react environment. The only difference would be maybe slight version differences in NPM/Node. I'm solving the problem by dockerising the project, shoudn't have any issues then. But... before I start work when I get home later, I'll read the errors. The first error was 'This folder doesn't contain a mobilehub project.' ... second error was related to missing files.

**Comment by UnleashedMind** [comment]
It's recommended that you get the latest CLI (v.1.1.1) first. 
After you pull your project at home, cd to the project root folder and execute 'awsmobile init <your mobile hub project id>' to set up the connection with your backend mobile hub project. 
You can find the mobile hub project id by going to the mobile hub console and choose your mobile hub project, the id appears in the url.

**Comment by michaelcuneo** [comment]
Looks like it might be my setup somewhere... I just installed a brand new react.js project at home. ran awsmobile init <ID> ... and the exact same error occurred.

**Comment by michaelcuneo** [comment]
It's o.k. I fixed my environment, for some reason I had an old version of Node... dunno what happened there.

**Comment by UnleashedMind** [comment]
I'm glad it's worked out for you. 
The cli requires node v7 + (prefers node 8.9.0), because it is using async/await.

**Comment by kaustavghosh06** [comment]
Closing this since it's resolved, please feel free to re-open if you still have issues.
