### ISSUE TITLE
cloud-api creation taking longer than expected... 

### ISSUE THREAD

**Issue by michaelcuneo** [aws/awsmobile-cli#107]
I ran an awsmobile cloud-api configure to generate a CRUD.
Then I ran awsmobile push to update the back end.

It's on Status Check 52: CREATE IN PROGRESS.

Back end still says 'CREATE ON PROGRESS.

the create has been going for over 20 minutes...

**Comment by elorzafe** [comment]
Hi @michaelcuneo I think there is a problem with cloud formation. Can you run ```awsmobile console``` click on Cloud Logic feature, then you will see the status of the cloudformation stack under **View resource details**.

**Comment by michaelcuneo** [comment]
It did the same thing yesterday, instead of creating my CRUD it just rolled back and messed everything up.

**Comment by elorzafe** [comment]
Sorry for the inconvenience. The problem yesterday was with IAM (outage). I tried ```awsmobile push``` this morning and is working correctly.

**Comment by michaelcuneo** [comment]
Mine is still reporting Current stack state is 'CREATE_IN_PROGRESS' I left it overnight...

**Comment by elorzafe** [comment]
I think that is a bug, can you kill (cmd+c) and try ```awsmobile push``` again. Sorry about that.

**Comment by michaelcuneo** [comment]
The actual AWS MobileHub Console is in this status... I'm not even running awsmobile client right now because it's still stuck on the console end since yesterday. 

<img width="1019" alt="createstuck" src="https://user-images.githubusercontent.com/12700009/38963851-3386de3c-43b7-11e8-9758-d456ddd16e35.png">

**Comment by michaelcuneo** [comment]
I'll delete the CloudFormation stack and start from scratch I think... something has messed up bad somewhere. Since yesterdays outage, it has completely messed up my project.
