### ISSUE TITLE
awsmobile init crashes with "Unexpected token function" in "\node_modules\awsmobile-cli\lib\init-steps\s2-choose-strategy.js:104"

### ISSUE THREAD

**Issue by ankitmhn** [aws/awsmobile-cli#109]
Hello, 
On attempting to recreate the tutorial [here](https://medium.com/react-native-training/react-native-authentication-in-depth-8d8c2e4ad81b). I have run into this error:

> C:\Users\Ankit\Documents\Hurestic\App\RN\hurestic>awsmobile init

>C:\Users\Ankit\AppData\Roaming\npm\node_modules\awsmobile-cli\lib\init-steps\s2-choose-strategy.js:104
>async function inquirerForValid(initInfo){
      ^^^^^^^^
>
>SyntaxError: Unexpected token function
>    at createScript (vm.js:56:10)
>    at Object.runInThisContext (vm.js:97:10)
>    at Module._compile (module.js:542:28)
>    at Object.Module._extensions..js (module.js:579:10)
>    at Module.load (module.js:487:32)
>    at tryModuleLoad (module.js:446:12)
>    at Function.Module._load (module.js:438:3)
>    at Module.require (module.js:497:17)
>    at require (internal/module.js:20:19)
>    at Object.<anonymous> (C:\Users\Ankit\AppData\Roaming\npm\node_modules\awsmobile-cli\lib\command-init.js:16:24)

**Comment by elorzafe** [comment]
Hi @ankitmhn awsmobile-cli will require node 8.9 and above
