### ISSUE TITLE
Managing multiple environments within awsmobile

### ISSUE THREAD

**Issue by oluomoniyi** [aws/awsmobile-cli#114]
Been using awsmobile for a bit now and loving it, just have a query/feature request.

Is there anyway to manage multiple environments within awsmobile e.g dev, QA, production?

Something like
awsmobile create new environment
awsmobile publish to new environment

**Comment by elorzafe** [comment]
Hi @oluomoniyi, Thanks for your feedback and I am glad that you like use the awsmobile-cli!

Currently managing multiple environments is supported, I will mark this as a feature-request.

**Comment by ianpogi5** [comment]
I would like to know the answer to this as well.

**Comment by funkfinger** [comment]
following this issue, as I too have this question. Would love to see something like `awsmobile publish --environment production` ...

**Comment by keithdmoore** [comment]
This is a really important feature that is currently missing.  Hopefully this gets addressed soon.  Meanwhile, we all have to implement some custom hack to be able to deploy to dev, staging, prod, etc.

**Comment by swaminator** [comment]
Hi all, I'm a PM at AWS. While we currently do not have support for environments there is a workaround here: https://stackoverflow.com/questions/50736739/how-to-handle-development-to-production-process-with-multiple-aws-services/50751535#50751535

If anyone is interested in signing up to a beta to try out new/unreleased features, let me know your email address and I'll get in touch!

**Comment by swaminator** [comment]
@oluomoniyi @keithdmoore @funkfinger @ianpogi5 Let me know if you'd be interested in chatting about multiple environments.

**Comment by davidfarinha** [comment]
I also require a multi-environment setup with my Amplify project- where it should be hosted in us-west-2 for dev and eu-west-1 for production. Any advice on this would be much appreciated! My email is davidfarinha@hotmail.co.uk

**Comment by rizerzero** [comment]
@swaminator Hi, i'm also interested here is my email jbe.persee@gmail.com 
Thank you.

**Comment by oluomoniyi** [comment]
Looks like this has been implemented now https://aws-amplify.github.io/docs/cli/multienv?sdk=js

👍

**Comment by swaminator** [comment]
The Amplify CLI now supports team workflows. If you're looking to use the Amplify CLI in conjunction with the Console, you can view the recommended workflow here: https://docs.aws.amazon.com/amplify/latest/userguide/multi-environments.html
