### ISSUE TITLE
awsmobile cli does not add the aws-exports.ts file to the .gitignore file

### ISSUE THREAD

**Issue by SagarMhatre** [aws/awsmobile-cli#118]
When I followed the guide at https://aws.github.io/aws-amplify/media/angular_guide , I noticed that the awsmobile cli adds aws-exports.js to the .gitignore file but not the aws-exports.ts

This will result into aws details getting pushed to public repositories, which could be misused.

For now, manually adding it to the .gitignore helps.

**Comment by UnleashedMind** [comment]
The CLI was only managing the files that are generated by itself. 
But this can be easily updated, and it will be in the next cli version.

**Comment by UnleashedMind** [comment]
this is resolved in the latest cli update v1.1.3
