### ISSUE TITLE
awsmobile publish, option to not open browser

### ISSUE THREAD

**Issue by quangv** [aws/awsmobile-cli#170]
Sometimes it's annoying for the browser to open after publish. Is there a setting to change this?

I tried:
```
    BROWSER=none awsmobile publish
```

`BROWSER=none` works for disabling browser opening for `create-react-app` start, but this doesn't work.

Are you open to a PR on this?

**Comment by kaustavghosh06** [comment]
Thanks for the feedback. Open to a PR on this for sure.

**Comment by UnleashedMind** [comment]
I've approved and merged the PR.
