### ISSUE TITLE
Cloud 9 - awsmobile pull doesn't copy #current to backend

### ISSUE THREAD

**Issue by jreedvygr** [aws/awsmobile-cli#18]
I've tried several times, but the "pull" doesn't copy the awsmobile/#current-backend-info tp awsmobile/backend 

global packages on Cloud9:
/home/ec2-user/.nvm/versions/node/v6.11.4/lib
├── aws-sam-local@0.2.2
├── awsmobile-cli@1.0.4
├── coffeescript@2.0.1
├── create-react-app@1.4.3
└── npm@5.6.0

**Comment by UnleashedMind** [comment]
We've identified the cause of this issue and published a fix (1.0.7). 
Please get the latest and try again.

**Comment by UnleashedMind** [comment]
Please follow these steps:

npm update -g awsmobile-cli
awsmobile -V (and make sure the version is 1.0.7)
cd you-project-folder
awsmobile pull

At this point the yaml file in the backend is restored. You should be able to continue your work as usual
