### ISSUE TITLE
Windows - Can't do any input

### ISSUE THREAD

**Issue by MichZipp** [aws/awsmobile-cli#186]
Hello,

when i try to configure my aws mobile hub project through the awsmobile cli, everytime I want to setup a new configuraten, for example create a new cloud-api, the cli return before I can do any input.

I tried the same on my linux machine, there it works fine. I already reinstalled the cli on my windows machine, but the error still occurs.

The screenshot shows an example, i wanted to create a new cloud api. The line to type in the api name appears but in the same time the cli returns. 

![unbenannt](https://user-images.githubusercontent.com/15633078/44617784-90d96980-a869-11e8-8484-8ceef3fce3b8.PNG)

**Comment by slaat** [comment]
Having the same issue here

**Comment by UnleashedMind** [comment]
What' your node version? We've had users reporting issues on Windows with Node version 10, and the work around was to downgrade node version to 8.9.x

**Comment by MichZipp** [comment]
I had node version 10.9.0 installed. The downgrade fixed the issue!
