### ISSUE TITLE
No support for different profiles/roles/accounts?

### ISSUE THREAD

**Issue by mbadran** [aws/awsmobile-cli#19]
My Mobile Hub app is deployed in a specific account which was created by AWS Organizations. To switch to this account, I assume an IAM role with STS, then I can interact with the services in that account.

I can do this with the AWS CLI using different profile configurations, but the AWS Mobile CLI doesn't seem to support this functionality. Every time I run an `awsmobile init <app_id>` command, the CLI goes to the master/root account and returns a 404 error.

```
failed to link to backend awsmobile project with id = <app_id>
{ NotFoundException: No such project exists : <app_id>
    at Object.extractError (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'No such project exists : <app_id>',
  code: 'NotFoundException',
  time: 2017-12-20T02:42:16.828Z,
  requestId: '643ef32f-e52f-11e7-9133-65e7232d24f1',
  statusCode: 404,
  retryable: false,
  retryDelay: 53.63213931743709 }
```

I've spent a few hours trying to get this to work, and also scoured the docs closely with no luck. Looking at the backend linking code (and AWS Client util), there seems to be no logic for using STS session tokens when an IAM role is supplied.

It would be great to have this functionality built in, as it is with the AWS CLI. Using different AWS accounts/environments is a best-practice that allows for separation of config, access, and data.

Thanks!

**Comment by mlabieniec** [comment]
@mbadran thanks for the feedback, support for cli profiles is in our backlog.

**Comment by UnleashedMind** [comment]
In the latest cli update (v 1.0.11), aws access configuration is per project, this allows use of different account/user for different project. 

v1.0.11 also supports the use of aws profile: 
`awsmobile configure aws --profile <profile name>`

**Comment by CodySwannGT** [comment]
Has anyone tested this?

```
$ awsmobile configure aws --profile shudideveloper

configure aws
Setting awsmobile-cli to use named profile: shudideveloper

profile shudideveloper is not found in aws-cli config file
aws-cli config file queried:
/Users/cody/.aws/config

Failed to set profile shudideveloper
```

```
$ cat /Users/cody/.aws/config

[default]
region = us-west-2
output = json

[shudideveloper]
role_arn = arn:aws:iam::336812193828:role/ShudiAccountAccessRole
source_profile = default
region = us-east-1
```

```
$ awsmobile --version

1.0.12
```

**Comment by UnleashedMind** [comment]
the awsmobile-cli named profile feature relies on the profiles stored in the ~/.aws folder. 
The following link will give you more information on aws named profile:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

You see that error because the profile is marked incorrectly, please use the following marks
[default]
region = us-west-2
output = json

[profile shudideveloper]
role_arn = arn:aws:iam::336812193828:role/ShudiAccountAccessRole
source_profile = default
region = us-east-1

Please note that profile marks are different in the two files inside ~/.aws
 ~/.aws/credentials uses [profileName]
~/.aws/config uses [profile profileName] for profiles other than the [default]

**Comment by CodySwannGT** [comment]
Yep. Sorry. I realized my error but was afk and couldn't update this ticket.

That said, the cli still appears to not work with roles as
```
$ awsmobile configure --profile whatever
```

Still creates a json file with blank spots for access key and secret and the app will not function until those are filled in.

Is that the intended behavior right now or am I missing something?

Side note - my team is loving this project. Great work.

**Comment by UnleashedMind** [comment]
Thanks
There was a bug reported on issue #60 that might be  related to what you see here. Its fix has already been published along with other two bug fixes. v 1.0.13.

**Comment by CodySwannGT** [comment]
Thanks. The appears to be different.

Here's what I did:

1) Upgraded to 1.0.13
2) Removed aws-info.json and project-info.json
3) Ran awsmobile push (which predictably gave me the error 'you are not working inside a valid awsmobilejs project')
4) ran awsmobile configure --profile shudideveloper

```
configure aws
Setting awsmobile-cli to use named profile: shudideveloper

Done
```
5) Ran awsmobile push - which gave me the same 'you are not working inside a valid awsmobilejs project' error. I did not expect this this time.

6) ran awsmobile configure project --profile shudideveloper - and got the same error again.

I "solved" this by restoring the project-info.json and rerunning awsmobile push

This gave me the prompt "missing aws account settings" 

If I selected "no" then I can't push.

If I select "yes", then I'm prompted to enter my accessKeyId and my secretAccessKey

But this is not what we're looking to do. We want awsmobile to be able to assume a role via sts and control pulls and pushes that way. In this fashion, there would never be a accessKeyId or secretAccessKey needed at all.

**Comment by UnleashedMind** [comment]
Thank you very much for your feedbacks.
It sounds like the intended behavior of the awsmobile cli for this upgrade. 
And if project-info.json file is missing, the cli will assume this project is not valid and will not work on it, that's why you saw that error message. 
As for automatically assuming a role via sts, we will update you once we have a decision on it.

**Comment by kcijezie-wedge** [comment]
Hi @UnleashedMind, Any updates yet?

**Comment by bradennapier** [comment]
kind of crazyz that multiple accounts it he standard for separating out your concerns and you only support default - especially weird that you ship a feature that doesnt actually exist?
 
there appears to be no way to actually work with multiple accounts

awsmobile init will always go to defualt and deelte any configuration you have already
you have no way of setting the profile

setting the profile using `awsmobile configure -p <profile>` sets the json but it doesnt actually work when running the init command that is givven when you create from the backend

no idea how to make this work now...
