### ISSUE TITLE
Transpile cloud-api/ through babel?

### ISSUE THREAD

**Issue by d0ruk** [aws/awsmobile-cli#2]
Hello,

Is this possible?

I took a quick look at the source, and couldn't find any apparent module to hook into the build process.

-d

**Comment by UnleashedMind** [comment]
you are right, the cli does not need to be transpiled by babel.

**Comment by d0ruk** [comment]
No, I mean running *my* code through babel in the ```awsmobile push``` command.

I traced the building process to [here](https://github.com/aws/awsmobile-cli/blob/master/lib/backend-operations/cloud-api-lambda-builder.js#L214).

Am I correct in thinking that function is what I need to modify to hook into the build process?

**Comment by UnleashedMind** [comment]
correct. 
before the lambda function is zipped, you need to make sure it has already been correctly built.
