### ISSUE TITLE
awsmobile run error "stderr maxBuffer exceeded" 

### ISSUE THREAD

**Issue by jaxondu** [aws/awsmobile-cli#3]
The project is using VueJS. If I use "awsmobile push" then "npm run start" there is no problem.

`> awsmobile run

building backend

Successfully built backend, build artifacts are saved at: 
/Users/me/project/awsmobilejs/.awsmobile/backend-build

no backend changes detected since last awsmobile update api call

retrieving the latest backend awsmobile project information
awsmobile project's details logged at: awsmobilejs/#current-backend-info/backend-details.json
awsmobile project's access information logged at: awsmobilejs/#current-backend-info/aws-exports.js
awsmobile project's access information copied to: src/aws-exports.js
awsmobile project's specifications logged at: awsmobilejs/#current-backend-info/mobile-hub-project.yml
contents in #current-backend-info/ is synchronized with the latest information in the aws cloud

frontend start command exec error:Error: stderr maxBuffer exceeded`

**Comment by UnleashedMind** [comment]
Thanks, this issue has been fixed.
