### ISSUE TITLE
Can't run React sample app - local backend specs appear to be corrupted

### ISSUE THREAD

**Issue by DanielApt** [aws/awsmobile-cli#33]
### Problem
I cannot run the React Sample app on the [AWS Mobile Hub page](https://console.aws.amazon.com/mobilehub/home?region=us-east-1#/). `awsmobile run` fails with the following error

```
can not locate mobile-hub-project file inside awsmobilejs/backend
local backend specs appear to be corrupted
```

I notice that `aws-mobile-react-sample/awsmobilejs/backend` is empty, however `#current-backend-info` is populated with:
```
- aws-exports.js
- backend-details.json
- mobile-hub-project.yml
```

### Set-up:
* `node`: 6.10.3
* `awsmobile-cli`: 1.0.3
* I select the correct AWS Profile by running `export AWS_PROFILE=profile-name`
* `awsmobile` cli configured to use the same AWS_PROFILE and creds as above
* `eu-west-2` region
* macOS High Sierra 10.13.1

### Steps to reproduce
1. Go to [AWS Mobile Hub](https://console.aws.amazon.com/mobilehub/home?region=us-east-1#/)
2. Select the *Restaurant Ordering* starter kit
3. Create `react-sample` project in *EU West (London)* region
4. `git clone https://github.com/awslabs/aws-mobile-react-sample.git`
5. (Once backend is set-up) Click Next (which brings me to *Step 3 of 4*.
6. `cd aws-mobile-react-sample`
7. `awsmobile init XXXXXXX`
    * Where is your project's source directory:  (src) : **client/src**
    * Where is your project's distribution directory that stores build artifacts:  (
build) : **accept default**
    * What is your project's build command:  (npm run-script build) **accept default**
    * What is your project's start command for local test run:  (npm run-script star
t) **accept default**
8. Backend links successfully
9. `awsmobile run`
10. Get the following error:
```
can not locate mobile-hub-project file inside awsmobilejs/backend
local backend specs appear to be corrupted
```

**Comment by Darkade** [comment]
I have the same issue, both with the sample app and when starting an app from scratch. Is this related to #16?

**Comment by michaellashinsky** [comment]
Same issue for me with environment:

OS: Windows 10
NodeJS: v9.3.0
npm: v5.5.1
awsmobile: v1.0.6
region: us-east-1

Get to the step:

Now that your web app is cloud enabled, let’s kick the tires and see it running in the cloud.
Test your web app locally
First, make sure your app is functioning okay on your local environment.
> awsmobile run

and I get same error as OP  only difference is I dont provide a AWS profile and I accepted all defaults at the init dialogue.

**Comment by UnleashedMind** [comment]
We've identified one possible cause of this issue and published a fix, please update the awsmobile-cli to the latest version 1.0.7 (published today), and try again.

**Comment by UnleashedMind** [comment]
Please follow these steps: 

npm update -g awsmobile-cli
awsmobile -V (and make sure the version is 1.0.7)
cd <your project folder>
awsmobile pull

At this point the yaml file in the backend is restored. You should be able to continue your work as usual

**Comment by michaellashinsky** [comment]
Thanks @UnleashedMind this seems to have corrected the issues I was seeing.

**Comment by DanielApt** [comment]
Works for me as well! — Had some small issues with the instructions, where is the right place to comment on that?
