### ISSUE TITLE
Can't initialize backend behind proxy

### ISSUE THREAD

**Issue by b-ritter** [aws/awsmobile-cli#35]
I have been able to successfully create an app according to the [these steps](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/web-getting-started.html) in the AWS Mobile Hub getting started guide. However, when I am behind my corporate proxy, I get the following error when running

``` 
awsmobile init

backend awsmobile project creation error
{ Error: connect ETIMEDOUT xx.xx.xx.xx:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  message: 'connect ETIMEDOUT xx.xx.xx.xx:443',
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'xx.xx.xx.xx',
  port: 443,
  region: 'us-east-1',
  hostname: 'mobile.us-east-1.amazonaws.com',
  retryable: true,
  time: 2018-01-08T17:55:19.570Z }
```

I have verified that my environment variables are correct. I can even get a response via the aws cli. 
```
$ aws ec2 describe-instances
{
    "Reservations": [
        {
            "Instances": [
                {
                    "Monitoring": {
                        "State": "disabled"
                    }...
```
Any help would be greatly appreciated!

**Comment by mlabieniec** [comment]
@b-ritter It looks like your firewall may be blocking the mobile.us-east-1.amazonaws.com host (which is different from that ec2 endpoint your querying). Can you try with the latest CLI:

    $ aws mobile list-projects

This may at least verify that this hostname is being blocked or not.

**Comment by b-ritter** [comment]
Thank you for taking a look. Here is what I get for projects I created from outside the proxy:

```
$ aws mobile list-projects
{
    "projects": [
        {
            "projectId": "1234",
            "name": "2018-01-08-18-15-45"
        },
        {
            "projectId": "5678",
            "name": "foo"
        }
    ]
}
```

**Comment by mlabieniec** [comment]
@b-ritter thanks for trying that. I'm assuming thats with the same cli setup/location as you are using for the awsmobile-cli? I'm checking internally here to see what might be happening. Can you confirm your still getting the error with the awsmobile-cli when running init?

**Comment by b-ritter** [comment]
Yes that is with the same cli setup and location. I tried again and I am getting the same error. Thanks again!

**Comment by mlabieniec** [comment]
@b-ritter i checked here and it sounds like the aws cli may actually use a different host for it's calls...the only thing I can think of is that either your firewall is blocking the host "mobile.us-east-1.amazonaws.com", or the IPs that this host is resolving to may not be allowed by your proxy. Can you check with your IT and see if this may be the case? Also, perhaps you can try pinging that host to validate this theory. Let me know.

**Comment by b-ritter** [comment]
@mlabieniec thanks again for your help. That host is indeed being blocked by our proxy. (Running `tracert` clearly shows this is the case.) I had assumed that aws hosts would be in the clear since `aws mobile list-projects` worked.
