### ISSUE TITLE
Different urls are shown `awsmobile publish` and AWS console for S3

### ISSUE THREAD

**Issue by yuyokk** [aws/awsmobile-cli#46]
Hi guys,

After `awsmobile publish` I see the following message 

```
Successful!
your application is published and hosted at:
http://affiliates-hosting-mobilehub-453285650.s3-website.us-east-1.amazonaws.com
```

But when I go to AWS console I see slightly different url of the S3 bucket
http://affiliates-hosting-mobilehub-453285650.s3-website-us-east-1.amazonaws.com

Please see screenshot attached
![screenshot 2018-01-22 23 09 48](https://user-images.githubusercontent.com/1225343/35244718-d4c29a7a-ffc9-11e7-9c17-4501dcb0c0b4.png)

It's not a big of the issue for sure but just wanted to report it.

Thanks

**Comment by UnleashedMind** [comment]
Thanks, we are investigating this issue.

**Comment by nidsharm** [comment]
Hi @yuyokk ,

Thank you for bringing this to our attention. The correct s3 url is the one displayed by the CLI (http://affiliates-hosting-mobilehub-453285650.s3-website.us-east-1.amazonaws.com), however the Mobile Hub version works too for us-east-1. We have added the bug fix for Mobile Hub to our backlog.
