### ISSUE TITLE
Default distribution directory: build instead of dist?

### ISSUE THREAD

**Issue by baharev** [aws/awsmobile-cli#5]
Since the examples use React, and the default distribution directory with React is build and not dist, it might be worth changing the default in awsmobile to build. As it currently is, one first gets an error with 

`awsmobile publish`

and after the error, newcomers have to run 

`awsmobile configure project`

to reconfigure the project. I expect most newcomers to fall into this trap. 

This is only a minor pain point and it is easy to correct, but fixing it in awsmobile would improve the first impression and the overall customer experience.

**Comment by mlabieniec** [comment]
@baharev when running `awsmobile init` the question/answer can be overridden by typing 'build' when the question is asked.

**Comment by baharev** [comment]
@mlabieniec Yes, I know that you can change it; I also wrote that in my original post. I am complaining about the **default** being `dist` and not `build`. All other defaults are perfect for React, and the examples also use React, so I see this particular default as an annoying stumbling block.
