### ISSUE TITLE
Increase Lambda execution timeout by default

### ISSUE THREAD

**Issue by yuyokk** [aws/awsmobile-cli#53]
Hi guys,

Last couple days I've been facing the issue when my requests were failing randomly with `statusCode: 502`

After some investigation I see that Lambda execution timeout is set to 3 seconds (I guess it's a default one) meaning all other longer requests will be rejected.

![image](https://user-images.githubusercontent.com/1225343/35829757-9ac277ba-0acc-11e8-96fd-8be7997be3ee.png)

I think it makes sense to increase this number to 10 or 30 seconds by default. Or maybe add an option to the cli while configuring API Getaway feature?

Please let me know your thoughts on this.
Thank you!

**Comment by elorzafe** [comment]
Hi @yuyokk 

Thanks for your feedback, we can add a configuration setting on the cli for this. I will set this as a feature request.

**Comment by elorzafe** [comment]
@yuyokk you can modify manually mobile-hub-project.yml to increase the timeout, and then run awsmobile push

**Comment by yuyokk** [comment]
@elorzafe that's what I actually did :D thanks for heads up!
