### ISSUE TITLE
awsmobile configure crashes on second run

### ISSUE THREAD

**Issue by zefre** [aws/awsmobile-cli#60]
Running `awsmobile configure` the first time, without a configuration present, prompts for an access ID immediately, and does not deep link to the console. Upon running `awsmobile configure` again, the program crashes. See attached screenshot for console output.
![screen shot 2018-02-09 at 10 43 11 pm](https://user-images.githubusercontent.com/18161749/36058625-35d69e0e-0deb-11e8-9048-2de9ed71e458.png)

**Comment by UnleashedMind** [comment]
Thanks for point it out. This is a bug. It happens when awsmobile-cli can not find or resolve configs in the ~/.aws folder. 
Bug fix has been pushed

**Comment by UnleashedMind** [comment]
The latest update (v 1.0.13) should have resolved this issue.
