### ISSUE TITLE
Unable to start react demo

### ISSUE THREAD

**Issue by teddarling** [aws/awsmobile-cli#62]
Trying to follow the instructions at https://github.com/awslabs/aws-mobile-react-sample to create a react app.

I start by issuing 
`awsmobile configure aws --profile my_profile`
to use my profile. I have also tested with just `awsmobile configure` to test things out

After configuring the CLI, and running `awsmobile start app react`, I expect an app inside the folder 'app'. Instead I get the following output from the command.

`Creating project app
Failed to download starter awslabs/aws-mobile-react-sample
error: 'git clone' failed with status 128`

So it just appears that somewhere it isn't able to download the starter to continue with. Based on the output, it seems that there is not a complete URL to the repository. That may not be the case, but something to look into and I will see what I can do just downloading the source and running `awsmobile init` instead

**Comment by collinforrester** [comment]
I was experiencing this same issue.  Found this comment here - https://github.com/flipxfx/download-git-repo/issues/19#issuecomment-365971553

As soon as I removed clone = true from the downloadGitRepo call, everything started working.

So in awsmobilestarter-manager: `downloadGitRepo(repo, tempDirPath, function (err) {`

You want a PR?

**Comment by UnleashedMind** [comment]
Thanks @collinforrester , we will remove the clone option in our next update, please send a PR.

**Comment by UnleashedMind** [comment]
@teddarling For now, please make sure your ssh key is properly setup for github
-  run `ssh-keygen` on your local terminal
- go to https://github.com/settings/keys and paste your public key there
- add github to your known host:  ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts

and do the following before you try again to make sure the cli has a clean slate
- close all IDEs such as VS Code or Eclipse
- remove ~/.awsmobilejs/temp

**Comment by UnleashedMind** [comment]
I'm closing this issue for now, feel free to re-open it if you still get this problem.
