### ISSUE TITLE
aws-exports.js should be in gitignore

### ISSUE THREAD

**Issue by ceich** [aws/awsmobile-cli#63]
Adrian Hall's [blog post](https://shellmonger.com/2018/01/15/implementing-mobile-authentication-with-react-native-and-amazon-cognito/) from last month said that the aws-exports.js file should not be checked in to source control. This suggests that it should be added to .gitignore by the CLI.

**Comment by UnleashedMind** [comment]
Thanks for pointing this out. 
This will be in the next update

**Comment by UnleashedMind** [comment]
this is already in the cli since version v 1.0.16. 
I'm closing this issue, feel free to re-open it if you see problem
