### ISSUE TITLE
Which files should be in .gitignore?

### ISSUE THREAD

**Issue by ildar-icoosoft** [aws/awsmobile-cli#66]
Tell me please which files from awsmobilejs I should store in git? awsmobile-cli added to gitignore this lines:
```
awsmobilejs/.awsmobile/backend-build
awsmobilejs/\#current-backend-info
```
If I don't add cloud-api in awsmobile features then there are not many files in git. But if I add cloud-api feature then there are > 4000 files in awsmobilejs/backend/cloud-api directory. Should I add this directory in .gitignore?

**Comment by elorzafe** [comment]
Hi @ildar-icoosoft 

Inside of cloud-api directory contains directories for each lambda function. Lambda functions contains a node_modules directory that you should add into your .gitignore.

You can modify your lambda functions at your will, awsmobile-cli provides some functionality to demonstrate the feature but is expected to be modified and that code is important to be versioned.

**Comment by ildar-icoosoft** [comment]
@elorzafe Thank you! I have a directory "sampleLambda" in cloud-api. I think awsmobile-cli should automatically add .gitignore file with node_modules ?

**Comment by UnleashedMind** [comment]
node_module are usually already put in the .gitignore file when the project is setup. 
the cli only insert into the .gitignore file the contents generated by itself.

**Comment by UnleashedMind** [comment]
closing the issue for now, feel free to re-open it or continue the conversation here.
