### ISSUE TITLE
Configuration conflicts in versioning

### ISSUE THREAD

**Issue by superandrew** [aws/awsmobile-cli#69]
When we share a awsmobile-cli project between developers, we find that 3 files are conflicting:
1. a json file in <user-home>/.awsmobilejs/project-aws-config/<PROJECTNAME>-xvOIo.json
2. <project-dir>/awsmobilejs/.awsmobile/info/aws-info.json
3. <project-dir>/awsmobilejs/.awsmobile/info/project-info.json

I'm not sure if we did something wrong, but in those files there are absolute references to path that contain the username, so the're not versioning-friendly.

We tried to change the path to relative (and to ~ for user home). But we've got errors:

    fs.js:663
      return binding.open(pathModule.toNamespacedPath(path),
                 ^

    Error: ENOENT: no such file or directory, open '~/.awsmobilejs/project-aws-config/<PROJECTNAME>-1ONfI.json'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at resolve_project_awsConfig 

Is this by design? Or are we doing something wrong? In the first case, probably it would be better to handle differently relative paths.

**Comment by UnleashedMind** [comment]
you can not change the info or the config files paths, those files are only meant to be used by the cli, and their paths are internally set by the cli. 
after v1.0.16, the cli separate the project config from the project info, and only project config file is supposed to be checked in. Collaborators set up their own backend mobile project by running `awsmobile init` on the project after cloning it from the github.  
Please check the release notes: 
https://github.com/aws/awsmobile-cli/releases

**Comment by UnleashedMind** [comment]
closing the issue for now, feel free to re-open it or continue the conversion here.

**Comment by goatandsheep** [comment]
@UnleashedMind is there any way to change the config after it has been initialized? For example, if one team member has setup a graphql instance and you want to switch to it from another
