### ISSUE TITLE
Incorrect URL for the published and hosted application

### ISSUE THREAD

**Issue by baharev** [aws/awsmobile-cli#7]
After running `awsmobile publish` I get:

> your application is published and hosted at:
> http://project_name-hosting-mobilehub-123456789.s3-website-eu-central-1.amazonaws.com

which is incorrect. The correct URL is:

https://s3.eu-central-1.amazonaws.com/project_name-hosting-mobilehub-123456789

**Comment by elorzafe** [comment]
The url you mention there is the bucket url, but on s3 when you enable static website hosting the url for that purpose is the one that is specified on the cli (the cli is assuming you are using index.html for your homepage).

**Comment by baharev** [comment]
@elorzafe Sorry, I don't follow. I am using everything with it's default settings, and I am using `index.html` for my homepage. The default behavior is what I write in my first post, and it does not seem OK to me.

Please elaborate and tell me what to change.

**Comment by elorzafe** [comment]
This is fixed now on the github code. Soon we will release this fix on npm. Thanks!

**Comment by mlabieniec** [comment]
Fixed in #28
