### ISSUE TITLE
The 'you are not working inside a valid awsmobilejs project' error occurs after a pull from git

### ISSUE THREAD

**Issue by shurmanidze** [aws/awsmobile-cli#83]
I've created a project using awsmobile CLI and pushed it to my git repo. Once I pull the repo on my another PC and try to run it I get this:

```
$ awsmobile run

you are not working inside a valid awsmobilejs project
```

As I see it checks the `project-info.json` file that is in `.gitignore`:

```
#awsmobilejs
aws-info.json
project-info.json
aws-exports.js
awsmobilejs/.awsmobile/backend-build
awsmobilejs/\#current-backend-info
~awsmobilejs-*/
```

**Comment by UnleashedMind** [comment]
you have to run `awsmobile init <backenc-mobile-project-id>` on the project after you pull it, then it becomes a valid awsmobilejs project.

**Comment by shurmanidze** [comment]
Thanks, it's working this way. BTW is there the project-id somewhere in the Console UI? I managed to find it just in the project details page URL.

**Comment by UnleashedMind** [comment]
It appears in the console url as you've found. It's not in the UI.

**Comment by UnleashedMind** [comment]
closing the issue for now, feel free to open other issues for questions or bugs.
