### ISSUE TITLE
awsmobile publish silently overwrites changes made online in the console

### ISSUE THREAD

**Issue by baharev** [aws/awsmobile-cli#9]
I added User Data Storage to my app online in the browser. I forgot to `awsmobile pull` before running `awsmobile publish`. This then simply deleted *without any warning* the `<project name>-userfiles-mobilehub-123456789` S3 bucket. I personally find it a very confusing default behavior. At least a warning would have been helpful that I am about to discard a bucket.

**Comment by domZippilli** [comment]
FWIW, I suspect `publish` and `run` probably run some of the same code, and very similar "silent overwrite" is documented in #12 -- though in that case, the integration with an imported API is erased on `run` despite a `pull`.

**Comment by elorzafe** [comment]
These issue is now fixed on github current codebase. We will soon release a new version of the npm package (1.0.5) with this fix.

**Comment by elorzafe** [comment]
Version 1.0.5 release. Fix is published!

**Comment by domZippilli** [comment]
@elorzafe does this also fix #12?
