### ISSUE TITLE
awsmobile user-signin enable --prompt advance settings option does not set the mfa-configuration in mobile-hub-project.yml file

### ISSUE THREAD

**Issue by SagarMhatre** [aws/awsmobile-cli#91]
$ awsmobile user-signin enable --prompt

? Sign-in is currently disabled, what do you want to do next **Go to advance settings**
? Which sign-in method you want to configure Cognito UserPools (currently disabled)
? How are users going to login Email
? Password minimum length (number of characters) 8
? Password character requirements uppercase, lowercase, numbers, special characters

$ awsmobile push
...
{ BadRequestException: MFA configuration cannot be blank. Attribute: mfa-configuration`

For now, I have manually inserted mfa-configuration: OFF below alias-attributes , above the name in the mobile-hub-project.yml file

**Comment by elorzafe** [comment]
This was fix on version 1.1.0
